Build: Cache windows and other libraries separately and using their actual version name (which differs in Windows).

diff --git a/.github/workflows/cache_libs.yml b/.github/workflows/cache_libs.yml
--- a/.github/workflows/cache_libs.yml
+++ b/.github/workflows/cache_libs.yml
@@ -19,6 +19,22 @@ on:
         default: "1.1.43"
         required: false
         type: string
+      WIN_ZLIB_VERSION:
+        default: "1.3.1"
+        required: false
+        type: string
+      WIN_LIBICONV_VERSION:
+        default: "1.17.1"
+        required: false
+        type: string
+      WIN_LIBXML2_VERSION:
+        default: "2.11.9"
+        required: false
+        type: string
+      WIN_LIBXSLT_VERSION:
+        default: "1.1.39"
+        required: false
+        type: string
 
     outputs:
       ZLIB_VERSION:
@@ -29,6 +45,14 @@ on:
         value: ${{ inputs.LIBXML2_VERSION }}
       LIBXSLT_VERSION:
         value: ${{ inputs.LIBXSLT_VERSION }}
+      WIN_ZLIB_VERSION:
+        value: ${{ inputs.WIN_ZLIB_VERSION }}
+      WIN_LIBICONV_VERSION:
+        value: ${{ inputs.WIN_LIBICONV_VERSION }}
+      WIN_LIBXML2_VERSION:
+        value: ${{ inputs.WIN_LIBXML2_VERSION }}
+      WIN_LIBXSLT_VERSION:
+        value: ${{ inputs.WIN_LIBXSLT_VERSION }}
 
 
 jobs:
@@ -46,10 +70,10 @@ jobs:
     runs-on: ${{ matrix.os }}
 
     env:
-      ZLIB_VERSION: ${{ inputs.ZLIB_VERSION }}
-      LIBICONV_VERSION: ${{ inputs.LIBICONV_VERSION }}
-      LIBXML2_VERSION: ${{ inputs.LIBXML2_VERSION }}
-      LIBXSLT_VERSION: ${{ inputs.LIBXSLT_VERSION }}
+      ZLIB_VERSION: ${{ contains(matrix.os, 'windows-') && inputs.WIN_ZLIB_VERSION || inputs.ZLIB_VERSION }}
+      LIBICONV_VERSION: ${{ contains(matrix.os, 'windows-') && inputs.WIN_LIBICONV_VERSION || inputs.LIBICONV_VERSION }}
+      LIBXML2_VERSION: ${{ contains(matrix.os, 'windows-') && inputs.WIN_LIBXML2_VERSION || inputs.LIBXML2_VERSION }}
+      LIBXSLT_VERSION: ${{ contains(matrix.os, 'windows-') && inputs.WIN_LIBXSLT_VERSION || inputs.LIBXSLT_VERSION }}
 
     steps:
     - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
@@ -67,3 +91,12 @@ jobs:
       env:
         GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       run: python3 buildlibxml.py --download-only
+
+    - name: Check Windows library versions
+      if: ${{ contains(matrix.os, 'windows-') }}
+      run: |
+        bash -c '
+        for file in  libs/zlib-${{ inputs.WIN_ZLIB_VERSION }}.*.zip  libs/iconv-${{ inputs.WIN_LIBICONV_VERSION }}.*.zip  libs/libxml2-${{ inputs.WIN_LIBXML2_VERSION }}.*.zip  libs/libxslt-${{ inputs.WIN_LIBXSLT_VERSION }}.*.zip; do
+            [[ -f "$file" ]] || { echo "MISSING: $file" ; exit 1; }
+        done
+        '
